/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtilhariaRouteImport } from './routes/artilharia'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as AtletasIndexRouteImport } from './routes/atletas.index'
import { Route as AtletasPlayerIdRouteImport } from './routes/atletas.$playerId'
import { Route as ClubesIndexRouteImport } from './routes/clubes.index'
import { Route as ClubesTeamIdRouteImport } from './routes/clubes.$teamId'
import { Route as JogosIndexRouteImport } from './routes/jogos.index'
import { Route as JogosMatchIdRouteImport } from './routes/jogos.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtilhariaRoute = ArtilhariaRouteImport.update({
  id: '/artilharia',
  path: '/artilharia',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasIndexRoute = AtletasIndexRouteImport.update({
  id: '/atletas/',
  path: '/atletas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasPlayerIdRoute = AtletasPlayerIdRouteImport.update({
  id: '/atletas/$playerId',
  path: '/atletas/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesIndexRoute = ClubesIndexRouteImport.update({
  id: '/clubes/',
  path: '/clubes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesTeamIdRoute = ClubesTeamIdRouteImport.update({
  id: '/clubes/$teamId',
  path: '/clubes/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosIndexRoute = JogosIndexRouteImport.update({
  id: '/jogos/',
  path: '/jogos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosMatchIdRoute = JogosMatchIdRouteImport.update({
  id: '/jogos/$matchId',
  path: '/jogos/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artilharia': typeof ArtilhariaRoute
  '/classificacao': typeof ClassificacaoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/noticias': typeof NoticiasRoute
  '/ranking': typeof RankingRoute
  '/atletas/$playerId': typeof AtletasPlayerIdRoute
  '/clubes/$teamId': typeof ClubesTeamIdRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/clubes/': typeof ClubesIndexRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artilharia': typeof ArtilhariaRoute
  '/classificacao': typeof ClassificacaoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/noticias': typeof NoticiasRoute
  '/ranking': typeof RankingRoute
  '/atletas/$playerId': typeof AtletasPlayerIdRoute
  '/clubes/$teamId': typeof ClubesTeamIdRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
  '/atletas': typeof AtletasIndexRoute
  '/clubes': typeof ClubesIndexRoute
  '/jogos': typeof JogosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artilharia': typeof ArtilhariaRoute
  '/classificacao': typeof ClassificacaoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/noticias': typeof NoticiasRoute
  '/ranking': typeof RankingRoute
  '/atletas/$playerId': typeof AtletasPlayerIdRoute
  '/clubes/$teamId': typeof ClubesTeamIdRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/clubes/': typeof ClubesIndexRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artilharia'
    | '/classificacao'
    | '/estatisticas'
    | '/noticias'
    | '/ranking'
    | '/atletas/$playerId'
    | '/clubes/$teamId'
    | '/jogos/$matchId'
    | '/atletas/'
    | '/clubes/'
    | '/jogos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artilharia'
    | '/classificacao'
    | '/estatisticas'
    | '/noticias'
    | '/ranking'
    | '/atletas/$playerId'
    | '/clubes/$teamId'
    | '/jogos/$matchId'
    | '/atletas'
    | '/clubes'
    | '/jogos'
  id:
    | '__root__'
    | '/'
    | '/artilharia'
    | '/classificacao'
    | '/estatisticas'
    | '/noticias'
    | '/ranking'
    | '/atletas/$playerId'
    | '/clubes/$teamId'
    | '/jogos/$matchId'
    | '/atletas/'
    | '/clubes/'
    | '/jogos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtilhariaRoute: typeof ArtilhariaRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  EstatisticasRoute: typeof EstatisticasRoute
  NoticiasRoute: typeof NoticiasRoute
  RankingRoute: typeof RankingRoute
  AtletasPlayerIdRoute: typeof AtletasPlayerIdRoute
  ClubesTeamIdRoute: typeof ClubesTeamIdRoute
  JogosMatchIdRoute: typeof JogosMatchIdRoute
  AtletasIndexRoute: typeof AtletasIndexRoute
  ClubesIndexRoute: typeof ClubesIndexRoute
  JogosIndexRoute: typeof JogosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artilharia': {
      id: '/artilharia'
      path: '/artilharia'
      fullPath: '/artilharia'
      preLoaderRoute: typeof ArtilhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/': {
      id: '/atletas/'
      path: '/atletas'
      fullPath: '/atletas/'
      preLoaderRoute: typeof AtletasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/$playerId': {
      id: '/atletas/$playerId'
      path: '/atletas/$playerId'
      fullPath: '/atletas/$playerId'
      preLoaderRoute: typeof AtletasPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes/': {
      id: '/clubes/'
      path: '/clubes'
      fullPath: '/clubes/'
      preLoaderRoute: typeof ClubesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes/$teamId': {
      id: '/clubes/$teamId'
      path: '/clubes/$teamId'
      fullPath: '/clubes/$teamId'
      preLoaderRoute: typeof ClubesTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/': {
      id: '/jogos/'
      path: '/jogos'
      fullPath: '/jogos/'
      preLoaderRoute: typeof JogosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/$matchId': {
      id: '/jogos/$matchId'
      path: '/jogos/$matchId'
      fullPath: '/jogos/$matchId'
      preLoaderRoute: typeof JogosMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtilhariaRoute: ArtilhariaRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  EstatisticasRoute: EstatisticasRoute,
  NoticiasRoute: NoticiasRoute,
  RankingRoute: RankingRoute,
  AtletasPlayerIdRoute: AtletasPlayerIdRoute,
  ClubesTeamIdRoute: ClubesTeamIdRoute,
  JogosMatchIdRoute: JogosMatchIdRoute,
  AtletasIndexRoute: AtletasIndexRoute,
  ClubesIndexRoute: ClubesIndexRoute,
  JogosIndexRoute: JogosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
