/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArtilhariaRouteImport } from './routes/artilharia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegulamentoRouteImport } from './routes/regulamento'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAtletaRouteImport } from './routes/_authenticated/atleta'
import { Route as AuthenticatedClubeRouteImport } from './routes/_authenticated/clube'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedVincularRouteImport } from './routes/_authenticated/vincular'
import { Route as AtletasIndexRouteImport } from './routes/atletas.index'
import { Route as AtletasPlayerIdRouteImport } from './routes/atletas.$playerId'
import { Route as ClubesIndexRouteImport } from './routes/clubes.index'
import { Route as ClubesTeamIdRouteImport } from './routes/clubes.$teamId'
import { Route as JogosIndexRouteImport } from './routes/jogos.index'
import { Route as JogosMatchIdRouteImport } from './routes/jogos.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtilhariaRoute = ArtilhariaRouteImport.update({
  id: '/artilharia',
  path: '/artilharia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulamentoRoute = RegulamentoRouteImport.update({
  id: '/regulamento',
  path: '/regulamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtletaRoute = AuthenticatedAtletaRouteImport.update({
  id: '/atleta',
  path: '/atleta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClubeRoute = AuthenticatedClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVincularRoute = AuthenticatedVincularRouteImport.update({
  id: '/vincular',
  path: '/vincular',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AtletasIndexRoute = AtletasIndexRouteImport.update({
  id: '/atletas/',
  path: '/atletas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasPlayerIdRoute = AtletasPlayerIdRouteImport.update({
  id: '/atletas/$playerId',
  path: '/atletas/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesIndexRoute = ClubesIndexRouteImport.update({
  id: '/clubes/',
  path: '/clubes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesTeamIdRoute = ClubesTeamIdRouteImport.update({
  id: '/clubes/$teamId',
  path: '/clubes/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosIndexRoute = JogosIndexRouteImport.update({
  id: '/jogos/',
  path: '/jogos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosMatchIdRoute = JogosMatchIdRouteImport.update({
  id: '/jogos/$matchId',
  path: '/jogos/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artilharia': typeof ArtilhariaRoute
  '/auth': typeof AuthRoute
  '/classificacao': typeof ClassificacaoRoute
  '/contato': typeof ContatoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/noticias': typeof NoticiasRoute
  '/ranking': typeof RankingRoute
  '/regulamento': typeof RegulamentoRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atleta': typeof AuthenticatedAtletaRoute
  '/clube': typeof AuthenticatedClubeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/vincular': typeof AuthenticatedVincularRoute
  '/atletas/$playerId': typeof AtletasPlayerIdRoute
  '/clubes/$teamId': typeof ClubesTeamIdRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/clubes/': typeof ClubesIndexRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artilharia': typeof ArtilhariaRoute
  '/auth': typeof AuthRoute
  '/classificacao': typeof ClassificacaoRoute
  '/contato': typeof ContatoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/noticias': typeof NoticiasRoute
  '/ranking': typeof RankingRoute
  '/regulamento': typeof RegulamentoRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atleta': typeof AuthenticatedAtletaRoute
  '/clube': typeof AuthenticatedClubeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/vincular': typeof AuthenticatedVincularRoute
  '/atletas/$playerId': typeof AtletasPlayerIdRoute
  '/clubes/$teamId': typeof ClubesTeamIdRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
  '/atletas': typeof AtletasIndexRoute
  '/clubes': typeof ClubesIndexRoute
  '/jogos': typeof JogosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/artilharia': typeof ArtilhariaRoute
  '/auth': typeof AuthRoute
  '/classificacao': typeof ClassificacaoRoute
  '/contato': typeof ContatoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/noticias': typeof NoticiasRoute
  '/ranking': typeof RankingRoute
  '/regulamento': typeof RegulamentoRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/atleta': typeof AuthenticatedAtletaRoute
  '/_authenticated/clube': typeof AuthenticatedClubeRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/vincular': typeof AuthenticatedVincularRoute
  '/atletas/$playerId': typeof AtletasPlayerIdRoute
  '/clubes/$teamId': typeof ClubesTeamIdRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/clubes/': typeof ClubesIndexRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artilharia'
    | '/auth'
    | '/classificacao'
    | '/contato'
    | '/estatisticas'
    | '/noticias'
    | '/ranking'
    | '/regulamento'
    | '/sobre'
    | '/admin'
    | '/atleta'
    | '/clube'
    | '/painel'
    | '/vincular'
    | '/atletas/$playerId'
    | '/clubes/$teamId'
    | '/jogos/$matchId'
    | '/atletas/'
    | '/clubes/'
    | '/jogos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artilharia'
    | '/auth'
    | '/classificacao'
    | '/contato'
    | '/estatisticas'
    | '/noticias'
    | '/ranking'
    | '/regulamento'
    | '/sobre'
    | '/admin'
    | '/atleta'
    | '/clube'
    | '/painel'
    | '/vincular'
    | '/atletas/$playerId'
    | '/clubes/$teamId'
    | '/jogos/$matchId'
    | '/atletas'
    | '/clubes'
    | '/jogos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/artilharia'
    | '/auth'
    | '/classificacao'
    | '/contato'
    | '/estatisticas'
    | '/noticias'
    | '/ranking'
    | '/regulamento'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/atleta'
    | '/_authenticated/clube'
    | '/_authenticated/painel'
    | '/_authenticated/vincular'
    | '/atletas/$playerId'
    | '/clubes/$teamId'
    | '/jogos/$matchId'
    | '/atletas/'
    | '/clubes/'
    | '/jogos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArtilhariaRoute: typeof ArtilhariaRoute
  AuthRoute: typeof AuthRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  ContatoRoute: typeof ContatoRoute
  EstatisticasRoute: typeof EstatisticasRoute
  NoticiasRoute: typeof NoticiasRoute
  RankingRoute: typeof RankingRoute
  RegulamentoRoute: typeof RegulamentoRoute
  SobreRoute: typeof SobreRoute
  AtletasPlayerIdRoute: typeof AtletasPlayerIdRoute
  ClubesTeamIdRoute: typeof ClubesTeamIdRoute
  JogosMatchIdRoute: typeof JogosMatchIdRoute
  AtletasIndexRoute: typeof AtletasIndexRoute
  ClubesIndexRoute: typeof ClubesIndexRoute
  JogosIndexRoute: typeof JogosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artilharia': {
      id: '/artilharia'
      path: '/artilharia'
      fullPath: '/artilharia'
      preLoaderRoute: typeof ArtilhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamento': {
      id: '/regulamento'
      path: '/regulamento'
      fullPath: '/regulamento'
      preLoaderRoute: typeof RegulamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atleta': {
      id: '/_authenticated/atleta'
      path: '/atleta'
      fullPath: '/atleta'
      preLoaderRoute: typeof AuthenticatedAtletaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clube': {
      id: '/_authenticated/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof AuthenticatedClubeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vincular': {
      id: '/_authenticated/vincular'
      path: '/vincular'
      fullPath: '/vincular'
      preLoaderRoute: typeof AuthenticatedVincularRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/atletas/': {
      id: '/atletas/'
      path: '/atletas'
      fullPath: '/atletas/'
      preLoaderRoute: typeof AtletasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/$playerId': {
      id: '/atletas/$playerId'
      path: '/atletas/$playerId'
      fullPath: '/atletas/$playerId'
      preLoaderRoute: typeof AtletasPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes/': {
      id: '/clubes/'
      path: '/clubes'
      fullPath: '/clubes/'
      preLoaderRoute: typeof ClubesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes/$teamId': {
      id: '/clubes/$teamId'
      path: '/clubes/$teamId'
      fullPath: '/clubes/$teamId'
      preLoaderRoute: typeof ClubesTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/': {
      id: '/jogos/'
      path: '/jogos'
      fullPath: '/jogos/'
      preLoaderRoute: typeof JogosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/$matchId': {
      id: '/jogos/$matchId'
      path: '/jogos/$matchId'
      fullPath: '/jogos/$matchId'
      preLoaderRoute: typeof JogosMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAtletaRoute: typeof AuthenticatedAtletaRoute
  AuthenticatedClubeRoute: typeof AuthenticatedClubeRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedVincularRoute: typeof AuthenticatedVincularRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtletaRoute: AuthenticatedAtletaRoute,
  AuthenticatedClubeRoute: AuthenticatedClubeRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedVincularRoute: AuthenticatedVincularRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArtilhariaRoute: ArtilhariaRoute,
  AuthRoute: AuthRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  ContatoRoute: ContatoRoute,
  EstatisticasRoute: EstatisticasRoute,
  NoticiasRoute: NoticiasRoute,
  RankingRoute: RankingRoute,
  RegulamentoRoute: RegulamentoRoute,
  SobreRoute: SobreRoute,
  AtletasPlayerIdRoute: AtletasPlayerIdRoute,
  ClubesTeamIdRoute: ClubesTeamIdRoute,
  JogosMatchIdRoute: JogosMatchIdRoute,
  AtletasIndexRoute: AtletasIndexRoute,
  ClubesIndexRoute: ClubesIndexRoute,
  JogosIndexRoute: JogosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
